# Generated by Django 3.2.9 on 2023-06-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='商品序号')),
                ('code', models.CharField(max_length=30, null=True, verbose_name='款号')),
                ('characteristic', models.CharField(max_length=255, null=True, verbose_name='特征')),
                ('exposure', models.IntegerField(null=True, verbose_name='曝光量')),
                ('clickExposure', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='曝光点击率')),
                ('clickDeal', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='点击成交率')),
                ('salesPrice', models.IntegerField(null=True, verbose_name='销售金额')),
                ('salesNum', models.IntegerField(null=True, verbose_name='件数')),
            ],
            options={
                'verbose_name': '直播间后台数据',
                'verbose_name_plural': '直播间后台数据',
                'db_table': 'taiwei_room',
            },
        ),
    ]
