# Generated by Django 3.2.9 on 2023-06-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='date_time',
            field=models.DateField(auto_now=True, verbose_name='直播日期'),
        ),
        migrations.AddField(
            model_name='room',
            name='session',
            field=models.CharField(max_length=10, null=True, verbose_name='第几场直播'),
        ),
    ]
