# Generated by Django 3.2.9 on 2023-06-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20230608_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='img',
            field=models.CharField(max_length=255, null=True, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='room',
            name='session',
            field=models.CharField(default='第一场', max_length=10, verbose_name='第几场直播'),
        ),
    ]
