# Generated by Django 3.2.9 on 2023-06-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_room_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='salesPrice',
            field=models.FloatField(null=True, verbose_name='销售金额'),
        ),
    ]
