# Generated by Django 3.2.9 on 2023-06-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_alter_room_salesprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='GPM',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='GPM'),
        ),
        migrations.AddField(
            model_name='room',
            name='back_rate',
            field=models.CharField(max_length=10, null=True, verbose_name='退款订单数占比'),
        ),
        migrations.AddField(
            model_name='room',
            name='clickDeal2',
            field=models.CharField(max_length=10, null=True, verbose_name='成交转化率'),
        ),
        migrations.AddField(
            model_name='room',
            name='order_number',
            field=models.IntegerField(null=True, verbose_name='广告结算订单数'),
        ),
        migrations.AddField(
            model_name='room',
            name='order_rate',
            field=models.CharField(max_length=10, null=True, verbose_name='广告结算订单率'),
        ),
    ]
