# Generated by Django 3.2.9 on 2023-06-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_auto_20230612_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, null=True, verbose_name='款号')),
                ('creation_date', models.DateField(null=True, verbose_name='创建日期')),
                ('size', models.CharField(max_length=255, null=True, verbose_name='尺寸')),
                ('season', models.CharField(max_length=20, null=True, verbose_name='季节')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='成本')),
                ('specification_sales', models.CharField(max_length=255, null=True, verbose_name='规格及销量')),
                ('available_quantity', models.IntegerField(null=True, verbose_name='可卖量')),
                ('stall_sales', models.IntegerField(null=True, verbose_name='档口销量')),
                ('stall_price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='档口价格')),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='订单价格')),
            ],
            options={
                'verbose_name': '整合表',
                'verbose_name_plural': '整合表',
                'db_table': 'taiwei_Integration',
            },
        ),
    ]
