# Generated by Django 3.2.9 on 2023-06-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='category',
            field=models.CharField(max_length=50, null=True, verbose_name='品类'),
        ),
    ]
