# Generated by Django 3.2.9 on 2023-06-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_integration_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='back_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=10, null=True, verbose_name='退款订单数占比'),
        ),
    ]
