# Generated by Django 3.2.9 on 2023-06-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_alter_room_back_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='back_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='退款订单数占比'),
        ),
        migrations.AlterField(
            model_name='room',
            name='clickDeal2',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='成交转化率'),
        ),
        migrations.AlterField(
            model_name='room',
            name='order_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='广告结算订单率'),
        ),
    ]
