# Generated by Django 3.2.9 on 2023-06-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_auto_20230616_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='back_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='退款订单数占比'),
        ),
        migrations.AlterField(
            model_name='room',
            name='order_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='广告结算订单率'),
        ),
    ]
