# Generated by Django 3.2.9 on 2023-06-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0013_auto_20230616_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='first_registration_time',
            field=models.DateField(null=True, verbose_name='初次到档口日期'),
        ),
        migrations.AddField(
            model_name='integration',
            name='last_registration_time',
            field=models.DateField(null=True, verbose_name='最后到档口日期'),
        ),
    ]
