# Generated by Django 4.2.2 on 2023-07-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0014_auto_20230616_1539"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=255, null=True, verbose_name="款号"),
                ),
                ("date", models.DateField(null=True, verbose_name="日期")),
                ("exposure_count", models.IntegerField(null=True, verbose_name="曝光量")),
                ("click_count", models.IntegerField(null=True, verbose_name="点击人数")),
                (
                    "total_exposure",
                    models.IntegerField(null=True, verbose_name="总曝光次数"),
                ),
                ("entry_count", models.IntegerField(null=True, verbose_name="进入次数")),
                (
                    "room_name",
                    models.CharField(max_length=20, null=True, verbose_name="直播间名称"),
                ),
            ],
            options={
                "verbose_name": "商品讲解信息",
                "verbose_name_plural": "商品讲解信息",
                "db_table": "taiwei_product_info",
            },
        ),
    ]
