# Generated by Django 4.2.2 on 2023-07-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0015_productinformation"),
    ]

    operations = [
        migrations.AddField(
            model_name="productinformation",
            name="live_time",
            field=models.CharField(max_length=255, null=True, verbose_name="讲解时间"),
        ),
    ]
