# Generated by Django 4.2.2 on 2023-07-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0017_productinformation_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="productinformation",
            name="click_rate",
            field=models.CharField(max_length=20, null=True, verbose_name="点击率"),
        ),
        migrations.AddField(
            model_name="productinformation",
            name="in_live_rate",
            field=models.CharField(max_length=20, null=True, verbose_name="进入率"),
        ),
        migrations.AddField(
            model_name="productinformation",
            name="success_reta",
            field=models.CharField(max_length=20, null=True, verbose_name="成交率"),
        ),
    ]
