# Generated by Django 4.2.2 on 2023-07-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0018_productinformation_click_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productinformation",
            name="pay_combo_cnt",
            field=models.IntegerField(null=True, verbose_name="销量"),
        ),
    ]
