# Generated by Django 4.2.2 on 2023-07-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0021_liveroomdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="liveroomdata",
            name="room_name",
            field=models.CharField(max_length=20, null=True, verbose_name="直播间名称"),
        ),
    ]
