# Generated by Django 4.2.2 on 2023-07-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0022_liveroomdata_room_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="cost",
            field=models.DecimalField(
                decimal_places=4, max_digits=10, null=True, verbose_name="成本"
            ),
        ),
        migrations.AlterField(
            model_name="integration",
            name="order_price",
            field=models.DecimalField(
                decimal_places=4, max_digits=10, null=True, verbose_name="订单价格"
            ),
        ),
        migrations.AlterField(
            model_name="integration",
            name="stall_price",
            field=models.DecimalField(
                decimal_places=4, max_digits=10, null=True, verbose_name="档口价格"
            ),
        ),
        migrations.AlterField(
            model_name="liveroomdata",
            name="ad_gmv",
            field=models.DecimalField(
                decimal_places=4, max_digits=10, null=True, verbose_name="广告GMV"
            ),
        ),
        migrations.AlterField(
            model_name="liveroomdata",
            name="ad_settlement_cost",
            field=models.DecimalField(
                decimal_places=4, max_digits=10, null=True, verbose_name="广告结算成本"
            ),
        ),
        migrations.AlterField(
            model_name="liveroomdata",
            name="click_deal_conversion_rate",
            field=models.DecimalField(
                decimal_places=4, max_digits=5, null=True, verbose_name="点击成交转化率"
            ),
        ),
        migrations.AlterField(
            model_name="liveroomdata",
            name="cumulative_deal_amount",
            field=models.DecimalField(
                decimal_places=4, max_digits=10, null=True, verbose_name="累计成交金额"
            ),
        ),
        migrations.AlterField(
            model_name="liveroomdata",
            name="expenditure",
            field=models.DecimalField(
                decimal_places=4, max_digits=10, null=True, verbose_name="消耗"
            ),
        ),
        migrations.AlterField(
            model_name="liveroomdata",
            name="product_ctr",
            field=models.DecimalField(
                decimal_places=4, max_digits=5, null=True, verbose_name="商品千次曝光成交"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="GPM",
            field=models.DecimalField(
                decimal_places=4, max_digits=10, null=True, verbose_name="GPM"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="order_rate",
            field=models.DecimalField(
                decimal_places=4, max_digits=10, null=True, verbose_name="广告结算订单率"
            ),
        ),
    ]
