# Generated by Django 4.2.2 on 2023-07-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0023_alter_integration_cost_alter_integration_order_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="liveroomdata",
            name="ad_deal_orders",
            field=models.IntegerField(null=True, verbose_name="广告成交订单数"),
        ),
    ]
