# Generated by Django 4.2.2 on 2023-07-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0025_alter_liveroomdata_click_deal_conversion_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liveroomdata",
            name="cumulative_deal_amount",
            field=models.DecimalField(
                decimal_places=4, max_digits=20, null=True, verbose_name="累计成交金额"
            ),
        ),
    ]
