# Generated by Django 4.2.2 on 2023-07-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0026_alter_liveroomdata_cumulative_deal_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liveroomdata",
            name="cumulative_deal_amount",
            field=models.IntegerField(null=True, verbose_name="累计成交金额"),
        ),
    ]
