# Generated by Django 4.2.2 on 2023-08-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DouyinUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("douyin_id", models.CharField(max_length=255, verbose_name="抖音ID")),
                (
                    "is_fan_group",
                    models.BooleanField(default=False, verbose_name="是否是粉丝团"),
                ),
                ("style_number", models.CharField(max_length=255, verbose_name="款号")),
                ("time", models.TimeField(verbose_name="时间")),
                ("date", models.DateField(verbose_name="日期")),
                ("username", models.CharField(max_length=255, verbose_name="用户名")),
            ],
            options={
                "verbose_name": "抖音用户",
                "verbose_name_plural": "抖音用户们",
                "db_table": "taiwei_douyin_user",
            },
        ),
    ]
