# Generated by Django 4.2.2 on 2023-08-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phone", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="douyinuser",
            name="date",
            field=models.DateField(auto_now=True, verbose_name="日期"),
        ),
        migrations.AlterField(
            model_name="douyinuser",
            name="time",
            field=models.IntegerField(verbose_name="时间"),
        ),
    ]
