# Generated by Django 4.2.2 on 2023-08-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phone", "0002_alter_douyinuser_date_alter_douyinuser_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="douyinuser",
            name="is_fan_group",
            field=models.SmallIntegerField(default=0, verbose_name="是否是粉丝团"),
        ),
    ]
