# Generated by Django 3.2.9 on 2023-06-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='名称')),
                ('date_time', models.CharField(max_length=10, null=True, verbose_name='最后提交时间')),
            ],
            options={
                'verbose_name': '最后上传时间',
                'verbose_name_plural': '最后上传时间',
                'db_table': 'taiwei_updatestatus',
            },
        ),
    ]
