# Generated by Django 3.2.9 on 2023-06-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_updatestatus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='moya_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='茉雅'),
        ),
    ]
