# Generated by Django 3.2.9 on 2023-06-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_ordertracking_moya_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='昵称')),
            ],
        ),
    ]
