# Generated by Django 3.2.9 on 2023-06-06 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_vipuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vipuser',
            options={'verbose_name': 'VIP用户', 'verbose_name_plural': 'VIP用户'},
        ),
        migrations.AlterModelTable(
            name='vipuser',
            table='taiwei_vipuser',
        ),
    ]
