# Generated by Django 3.2.9 on 2023-06-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20230606_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipuser',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='昵称'),
        ),
    ]
