# Generated by Django 3.2.9 on 2023-06-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_vipuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='number',
            field=models.IntegerField(null=True, verbose_name='总销量'),
        ),
    ]
