# Generated by Django 3.2.9 on 2023-06-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20230625_1029'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='repeatorder',
            table='taiwei_repeat_order',
        ),
    ]
