# Generated by Django 3.2.9 on 2023-06-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_repeatorder_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstyle',
            name='date',
            field=models.DateField(null=True, verbose_name='日期'),
        ),
    ]
