# Generated by Django 3.2.9 on 2023-06-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_newstyle_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstyle',
            name='order_maker',
            field=models.CharField(max_length=200, null=True, verbose_name='做下单表'),
        ),
        migrations.AlterField(
            model_name='repeatorder',
            name='code',
            field=models.CharField(max_length=200, null=True, verbose_name='款号'),
        ),
        migrations.AlterField(
            model_name='repeatorder',
            name='date',
            field=models.DateField(null=True, verbose_name='日期'),
        ),
    ]
