# Generated by Django 3.2.9 on 2023-06-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20230625_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstyle',
            name='code',
            field=models.CharField(max_length=200, null=True, verbose_name='款号'),
        ),
    ]
