# Generated by Django 3.2.9 on 2023-06-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='file_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='文件名'),
        ),
    ]
