# Generated by Django 3.2.9 on 2023-06-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_factory_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='num',
            field=models.FloatField(null=True, verbose_name='件数'),
        ),
    ]
