# Generated by Django 4.2.2 on 2023-06-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_factory_num"),
    ]

    operations = [
        migrations.CreateModel(
            name="styleStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateField(null=True, verbose_name="简报日期")),
                ("date_time", models.DateField(null=True, verbose_name="上传日期")),
                ("code", models.CharField(max_length=30, null=True, verbose_name="款号")),
                ("cai_chuang", models.IntegerField(null=True, verbose_name="裁床")),
                ("che_jian", models.IntegerField(null=True, verbose_name="车间")),
                ("hou_dao", models.IntegerField(null=True, verbose_name="后道")),
                ("tai_wei", models.IntegerField(null=True, verbose_name="泰维")),
                ("yi_fa", models.IntegerField(null=True, verbose_name="意法")),
                ("mo_ya", models.IntegerField(null=True, verbose_name="茉雅")),
                ("fabric_price", models.FloatField(null=True, verbose_name="面料金额")),
                ("materials_price", models.FloatField(null=True, verbose_name="辅料金额")),
                ("factory_price", models.FloatField(null=True, verbose_name="工厂金额")),
                (
                    "salesrecord_price",
                    models.FloatField(null=True, verbose_name="档口金额"),
                ),
                ("order_price", models.FloatField(null=True, verbose_name="订单金额")),
                (
                    "to_salesrecord_time",
                    models.DateField(null=True, verbose_name="最近到档口时间"),
                ),
                ("time_num", models.IntegerField(null=True, verbose_name="下单到今天天数")),
                ("tags", models.CharField(max_length=30, null=True, verbose_name="标签")),
            ],
            options={
                "verbose_name": "新款状态",
                "verbose_name_plural": "新款状态",
                "db_table": "taiwei_style_status",
            },
        ),
    ]
