# Generated by Django 4.2.2 on 2023-06-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_stylestatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stylestatus",
            name="date_time",
            field=models.DateField(auto_now=True, null=True, verbose_name="上传日期"),
        ),
    ]
