# Generated by Django 4.2.2 on 2023-06-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0024_alter_stylestatus_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stylestatus",
            name="date_time",
            field=models.DateField(null=True, verbose_name="上传日期"),
        ),
    ]
