# Generated by Django 4.2.2 on 2023-06-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0025_alter_stylestatus_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="stylestatus",
            name="remarks",
            field=models.TextField(null=True, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="stylestatus",
            name="tags",
            field=models.CharField(max_length=255, null=True, verbose_name="标签"),
        ),
    ]
