# Generated by Django 4.2.2 on 2023-06-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0026_stylestatus_remarks_alter_stylestatus_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="stylestatus",
            name="is_other",
            field=models.BooleanField(default=False, verbose_name="是否是其他"),
        ),
    ]
