# Generated by Django 4.2.2 on 2023-07-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0028_stylestatus_num"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newstyle",
            options={"verbose_name": "下单简报", "verbose_name_plural": "下单简报"},
        ),
    ]
