# Generated by Django 4.2.2 on 2023-07-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0030_alter_report_data_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="commodity",
            name="negative_review_rate",
            field=models.FloatField(null=True, verbose_name="差评率"),
        ),
        migrations.AddField(
            model_name="commodity",
            name="positive_review_count",
            field=models.IntegerField(null=True, verbose_name="好评数"),
        ),
        migrations.AddField(
            model_name="commodity",
            name="quality_return_rate",
            field=models.FloatField(null=True, verbose_name="品质退货率"),
        ),
    ]
