# Generated by Django 4.2.2 on 2023-07-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0031_commodity_negative_review_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewStyleStatusTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, null=True, verbose_name="款号")),
                ("order_date", models.DateField(null=True, verbose_name="下单日期")),
                ("total_quantity", models.IntegerField(null=True, verbose_name="总件数")),
                (
                    "status",
                    models.CharField(max_length=50, null=True, verbose_name="状态"),
                ),
                (
                    "label",
                    models.CharField(max_length=50, null=True, verbose_name="标签"),
                ),
                (
                    "caichaung_stock",
                    models.IntegerField(null=True, verbose_name="裁床库存"),
                ),
                ("chejian_stock", models.IntegerField(null=True, verbose_name="车间库存")),
                ("houdao_stock", models.IntegerField(null=True, verbose_name="后道库存")),
                ("taiwei_stock", models.IntegerField(null=True, verbose_name="泰维库存")),
                ("yifa_stock", models.IntegerField(null=True, verbose_name="意法库存")),
                ("moya_stock", models.IntegerField(null=True, verbose_name="茉雅库存")),
            ],
            options={
                "verbose_name": "新款状态跟踪",
                "verbose_name_plural": "新款状态跟踪",
                "db_table": "taiwei_new_style_ststaus_tracking",
            },
        ),
    ]
