# Generated by Django 4.2.2 on 2023-07-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0032_newstylestatustracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="newstylestatustracking",
            name="expected_date",
            field=models.DateField(null=True, verbose_name="预计日期"),
        ),
    ]
