# Generated by Django 4.2.2 on 2023-07-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0033_newstylestatustracking_expected_date"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="newstylestatustracking",
            table="taiwei_new_style_status_tracking",
        ),
    ]
