# Generated by Django 4.2.2 on 2023-07-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0034_alter_newstylestatustracking_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="newstylestatustracking",
            name="notes",
            field=models.CharField(max_length=255, null=True, verbose_name="备注"),
        ),
    ]
