# Generated by Django 4.2.2 on 2023-07-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0035_newstylestatustracking_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newstylestatustracking",
            old_name="caichaung_stock",
            new_name="caichuang_stock",
        ),
    ]
