# Generated by Django 4.2.2 on 2023-07-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0036_rename_caichaung_stock_newstylestatustracking_caichuang_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="newstylestatustracking",
            name="count",
            field=models.IntegerField(default=1, verbose_name="计数"),
        ),
    ]
