# Generated by Django 4.2.2 on 2023-07-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0037_newstylestatustracking_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="newstylestatustracking",
            name="auto_time",
            field=models.DateField(auto_now=True, verbose_name="自动生成的日期"),
        ),
    ]
