# Generated by Django 4.2.2 on 2023-07-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0038_newstylestatustracking_auto_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="describe",
            field=models.CharField(max_length=255, null=True, verbose_name="描述"),
        ),
    ]
