# Generated by Django 4.2.2 on 2023-08-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0040_rename_describe_goods_code_describe"),
    ]

    operations = [
        migrations.AddField(
            model_name="newstylestatustracking",
            name="notes_info",
            field=models.CharField(max_length=255, null=True, verbose_name="备注"),
        ),
    ]
