# Generated by Django 3.2.9 on 2023-06-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_code', models.CharField(blank=True, max_length=255, verbose_name='款号')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='货品名')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='图片')),
                ('order_quantity', models.IntegerField(blank=True, null=True, verbose_name='订购量')),
                ('workshop_quantity', models.CharField(blank=True, max_length=255, null=True, verbose_name='车间规格量')),
                ('post_processing_quantity', models.CharField(blank=True, max_length=255, null=True, verbose_name='后道规格量')),
                ('taiwei_yifa_moyajia_quantity', models.CharField(blank=True, max_length=255, null=True, verbose_name='泰维+意法+茉雅规格量')),
                ('pending_and_in_transit', models.IntegerField(blank=True, null=True, verbose_name='待发+在途')),
                ('cancelled', models.IntegerField(blank=True, null=True, verbose_name='取消')),
                ('successful', models.IntegerField(blank=True, null=True, verbose_name='成功')),
                ('returned', models.IntegerField(blank=True, null=True, verbose_name='退回')),
                ('live_deal_conversion_rate', models.FloatField(blank=True, null=True, verbose_name='直播间成交转化率')),
                ('exposure_click_rate', models.FloatField(blank=True, null=True, verbose_name='曝光点击率')),
                ('max_exposure_quantity', models.IntegerField(blank=True, null=True, verbose_name='最大曝光量')),
            ],
            options={
                'verbose_name': '购物车商品',
                'verbose_name_plural': '购物车商品',
                'db_table': 'taiwei_product',
            },
        ),
    ]
