# Generated by Django 3.2.9 on 2023-06-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='commodity_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='款号'),
        ),
    ]
