# Generated by Django 3.2.9 on 2023-06-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_product_commodity_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='post_processing_quantity_num',
            field=models.IntegerField(null=True, verbose_name='后道可卖量'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True, verbose_name='金额'),
        ),
        migrations.AddField(
            model_name='product',
            name='taiwei_yifa_moyajia_quantity_num',
            field=models.IntegerField(null=True, verbose_name='泰维+意法+茉雅可卖量'),
        ),
        migrations.AddField(
            model_name='product',
            name='workshop_quantity_num',
            field=models.IntegerField(null=True, verbose_name='车间可卖量'),
        ),
    ]
