# Generated by Django 3.2.9 on 2023-06-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_product_commodity_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_live_exposure_count',
            field=models.FloatField(blank=True, null=True, verbose_name='3天平均曝光量'),
        ),
    ]
