# Generated by Django 3.2.9 on 2023-06-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_product_prediction_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avg_live_exposure_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='3天平均曝光量'),
        ),
        migrations.AlterField(
            model_name='product',
            name='exposure_click_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='曝光点击率'),
        ),
    ]
