# Generated by Django 3.2.9 on 2023-06-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20230606_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='exposure_click_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='曝光点击率'),
        ),
        migrations.AlterField(
            model_name='product',
            name='live_deal_conversion_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='直播间成交转化率'),
        ),
    ]
