# Generated by Django 3.2.9 on 2023-06-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20230606_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True, verbose_name='订单应付金额'),
        ),
    ]
