# Generated by Django 3.2.9 on 2023-06-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_alter_product_commodity_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='来源'),
        ),
    ]
