/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    Update: typeof import('./src/components/Update.vue')['default']
    UpdateCodeLink: typeof import('./src/components/UpdateCodeLink.vue')['default']
    UpdateCommodity: typeof import('./src/components/UpdateCommodity.vue')['default']
    UpdateFabric: typeof import('./src/components/UpdateFabric.vue')['default']
    UpdateFactory: typeof import('./src/components/UpdateFactory.vue')['default']
    UpdateGoods: typeof import('./src/components/UpdateGoods.vue')['default']
    UpdateMaterials: typeof import('./src/components/UpdateMaterials.vue')['default']
    UpdateOneCommodity: typeof import('./src/components/UpdateOneCommodity.vue')['default']
    UpdateRepeatOredr: typeof import('./src/components/UpdateRepeatOredr.vue')['default']
    UpdateSalesRecord: typeof import('./src/components/UpdateSalesRecord.vue')['default']
    UpdateSize: typeof import('./src/components/UpdateSize.vue')['default']
    UpdateStock: typeof import('./src/components/UpdateStock.vue')['default']
    UpdateStockIn: typeof import('./src/components/UpdateStockIn.vue')['default']
    UpdateUser: typeof import('./src/components/UpdateUser.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
