# Generated by Django 4.2.2 on 2023-07-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Script",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, null=True, verbose_name="款号")),
                (
                    "name",
                    models.CharField(max_length=30, null=True, verbose_name="商品名"),
                ),
                (
                    "tags",
                    models.CharField(max_length=255, null=True, verbose_name="标签"),
                ),
                (
                    "material",
                    models.CharField(max_length=255, null=True, verbose_name="原始素材"),
                ),
                (
                    "ai_material",
                    models.CharField(max_length=255, null=True, verbose_name="加工素材"),
                ),
            ],
            options={
                "verbose_name": "商品话术",
                "verbose_name_plural": "商品话术",
                "db_table": "taiwei_script",
            },
        ),
    ]
