# Generated by Django 4.2.2 on 2023-07-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Script", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Design",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, null=True, verbose_name="款号")),
                (
                    "name",
                    models.CharField(max_length=30, null=True, verbose_name="货品名"),
                ),
                (
                    "designer",
                    models.CharField(max_length=255, null=True, verbose_name="设计师"),
                ),
                (
                    "material",
                    models.CharField(max_length=255, null=True, verbose_name="季节"),
                ),
                (
                    "specification_quantity",
                    models.CharField(max_length=255, null=True, verbose_name="规格数量"),
                ),
            ],
            options={
                "verbose_name": "商品话术",
                "verbose_name_plural": "商品话术",
                "db_table": "taiwei_design",
            },
        ),
        migrations.DeleteModel(
            name="Script",
        ),
    ]
