# Generated by Django 4.2.2 on 2023-07-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Script", "0002_design_delete_script"),
    ]

    operations = [
        migrations.AddField(
            model_name="design",
            name="cart_name",
            field=models.CharField(max_length=30, null=True, verbose_name="购物车名称"),
        ),
    ]
