# Generated by Django 4.2.2 on 2023-07-17 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Script", "0003_design_cart_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="design",
            options={"verbose_name": "商品设计", "verbose_name_plural": "商品设计"},
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        default="1,2,3,4,5,6", max_length=30, verbose_name="标签"
                    ),
                ),
                (
                    "design_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="Script.design",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品设计标签",
                "verbose_name_plural": "商品设计标签",
                "db_table": "taiwei_design_tags",
            },
        ),
    ]
