# Generated by Django 4.2.2 on 2023-07-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Script", "0004_alter_design_options_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tags",
            old_name="design_id",
            new_name="design",
        ),
    ]
