# Generated by Django 4.2.2 on 2023-07-17 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Script", "0006_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="size",
            name="tags",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="size",
                to="Script.tags",
            ),
            preserve_default=False,
        ),
    ]
