# Generated by Django 4.2.2 on 2023-07-17 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Script", "0007_size_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Script",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_type", models.IntegerField(verbose_name="标签类型")),
                (
                    "original",
                    models.CharField(max_length=255, null=True, verbose_name="原话语"),
                ),
                (
                    "gpt_original",
                    models.CharField(max_length=255, null=True, verbose_name="gpt加工话语"),
                ),
                (
                    "tags",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="script",
                        to="Script.tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品设计话术",
                "verbose_name_plural": "商品设计话术",
                "db_table": "taiwei_design_script",
            },
        ),
    ]
