# Generated by Django 4.2.2 on 2023-07-17 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Script", "0009_rename_tag_type_script_type_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lookOne",
                    models.CharField(max_length=255, null=True, verbose_name="款号1"),
                ),
                (
                    "lookTwo",
                    models.CharField(max_length=255, null=True, verbose_name="款号2"),
                ),
                (
                    "lookThree",
                    models.CharField(max_length=255, null=True, verbose_name="款号3"),
                ),
                (
                    "tags",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collocation",
                        to="Script.tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品搭配",
                "verbose_name_plural": "商品搭配",
                "db_table": "taiwei_design_collocation",
            },
        ),
    ]
