# Generated by Django 4.2.2 on 2023-07-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Script", "0010_collocation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collocation",
            name="lookOne",
        ),
        migrations.RemoveField(
            model_name="collocation",
            name="lookThree",
        ),
        migrations.RemoveField(
            model_name="collocation",
            name="lookTwo",
        ),
        migrations.AddField(
            model_name="collocation",
            name="codes",
            field=models.CharField(max_length=255, null=True, verbose_name="款号"),
        ),
    ]
