# Generated by Django 4.2.2 on 2023-07-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Script", "0011_remove_collocation_lookone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collocation",
            name="codes",
            field=models.CharField(default="", max_length=255, verbose_name="款号"),
        ),
    ]
