# Generated by Django 4.2.2 on 2023-07-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Script", "0014_remove_script_type_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="collocation",
            name="child_code",
            field=models.CharField(max_length=255, null=True, verbose_name="子款号"),
        ),
        migrations.AlterField(
            model_name="tags",
            name="tags",
            field=models.CharField(max_length=30, verbose_name="标签"),
        ),
    ]
