# Generated by Django 4.2.2 on 2023-07-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Script", "0015_collocation_child_code_alter_tags_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="collocation",
            name="is_del",
            field=models.SmallIntegerField(default=0, verbose_name="是否删除"),
        ),
    ]
