# Generated by Django 4.2.2 on 2023-07-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Script", "0016_collocation_is_del"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collocation",
            name="is_del",
        ),
    ]
