# Generated by Django 4.2.2 on 2023-07-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Script", "0017_remove_collocation_is_del"),
    ]

    operations = [
        migrations.AlterField(
            model_name="script",
            name="gpt_original",
            field=models.CharField(max_length=1000, null=True, verbose_name="gpt加工话语"),
        ),
        migrations.AlterField(
            model_name="script",
            name="original",
            field=models.CharField(max_length=1000, null=True, verbose_name="原话语"),
        ),
    ]
