# Generated by Django 4.2.2 on 2023-07-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Script", "0018_alter_script_gpt_original_alter_script_original"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="design",
            name="cart_name",
        ),
    ]
