# Generated by Django 4.2.2 on 2023-08-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Script", "0023_tags_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tags",
            name="notes",
        ),
    ]
