# Generated by Django 4.2.2 on 2023-08-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Script", "0024_remove_tags_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="tags",
            name="notes",
            field=models.CharField(
                default="请输入整体描述", max_length=255, null=True, verbose_name="描述"
            ),
        ),
    ]
